server:
  port: 8301
spring:
  application:
    name: ribbon-service
  zipkin:
    base-url: http://172.18.215.184:9411
  sleuth:
    sampler:
      probability: 1 #设置sleuth的抽样收集概率
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

service-url:
  user-service: http://user-service
